# Very basic variables and types

In [6]:
println("Hello there")

Hello there


In [2]:
my_var = 42
typeof(my_var)

Int64

In [4]:
my_f = 1.234
typeof(my_f)

Float64

In [5]:
# Julia fully supports unicode so we can do things like this
😸 = "cat"
typeof(😸)

String

In [7]:
# single line comments with #
#=
Multi line comments with #==#
=#

In [9]:
# basic math ops also work, notably ^
power = 10 ^ 2

100

In [11]:
days = 365
days_float = convert(Float64, days) 

365.0

In [12]:
@assert days == 365
@assert days_float == 365.0

In [13]:
convert(Int64, "1")

MethodError: MethodError: Cannot `convert` an object of type String to an object of type Int64
Closest candidates are:
  convert(::Type{T}, !Matched::Ptr) where T<:Integer at pointer.jl:23
  convert(::Type{T}, !Matched::T) where T<:Number at number.jl:6
  convert(::Type{T}, !Matched::Number) where T<:Number at number.jl:7
  ...

In [14]:
parse(Int64, "1")

1

# Strings

In [1]:
s1 = "I am a string"

"I am a string"

In [2]:
s2 = """I am also a string
I can go over multiple lines
"""

"I am also a string\nI can go over multiple lines\n"

In [3]:
println(typeof(s1))
println(typeof(s2))

String
String


In [4]:
# single quotes define a char
char = 'a'
println(typeof(char))

Char


In [5]:
'This will raise and error'

ErrorException: syntax: character literal contains multiple characters

In [6]:
# string interpolation is enabled by default
a = 1
b = 2
println("a is $a and b is $b, their sum is $(a + b)")


a is 1 and b is 2, their sum is 3


In [8]:
# strings can be concatenated in many ways
string("one ", "two ", 3) # this concatenates literals and converts non string values

"one two 3"

In [11]:
# we can also use * interpolation
s3 = "hi "
s4 = "there"
s3 * s4

"hi there"

# Data Structures

In [13]:
# dictionaries - create with Dict keyword
d = Dict("Jenny" => "123", "Satan" => "666") # the keys and values here are totally dynamic
# adding elements means just calling
d["Kramer"] = "234"
d

Dict{String, String} with 3 entries:
  "Jenny"  => "123"
  "Satan"  => "666"
  "Kramer" => "234"

In [15]:
# calling follows the same convention as calling
d["Satan"]

"666"

In [17]:
# uninitialised elements will throw errors
d["Not there"]

KeyError: KeyError: key "Not there" not found

In [21]:
# use get in stead (collection, key, default)
get(d, "Not here", "777")

"777"

In [19]:
# remove key value pairs with the pop! function
pop!(d, "Jenny")
d

Dict{String, String} with 2 entries:
  "Satan"  => "666"
  "Kramer" => "234"

# Tuples
!! NB NB NB Julia is 1 indexed !!

In [22]:
# tuples by enclosing in ()
animals = ("Bird", "Dog", "Cat")

("Bird", "Dog", "Cat")

In [26]:
# tuples are immutable
animals[1] = "Shark"

MethodError: MethodError: no method matching setindex!(::Tuple{String, String, String}, ::String, ::Int64)

In [25]:
animals[1]

"Bird"

In [27]:
# they can also be destructed
b, d, c = animals

("Bird", "Dog", "Cat")

In [28]:
b

"Bird"

# Arrays

In [29]:
# arrays are mutable, ordered and completely dynamic
a = [1, 2, 3, "hello"]

4-element Vector{Any}:
 1
 2
 3
  "hello"

In [30]:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [32]:
b = [('!', [1, 2, "hello"]), Dict(1 => 2)]

2-element Vector{Any}:
 ('!', Any[1, 2, "hello"])
 Dict(1 => 2)

In [33]:
b[1] = 1

1

In [34]:
b

2-element Vector{Any}:
 1
  Dict(1 => 2)

In [35]:
a

3-element Vector{Int64}:
 1
 2
 3

In [36]:
# add with push and remove with pop
push!(a, 42)

4-element Vector{Int64}:
  1
  2
  3
 42

In [37]:
popped = pop!(a)

42

In [38]:
popped

42

In [39]:
# multi dimensional arrays also behave as expected
m = [[1, 2, 3], [4, 5, 6]]

2-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5, 6]

In [41]:
rand(3, 4) # note that this is a matrix type

3×4 Matrix{Float64}:
 0.331512  0.151104  0.166486  0.706234
 0.284817  0.322246  0.88764   0.0714917
 0.233982  0.225516  0.246527  0.102621

In [43]:
push!(a, 1, 2) # push can also take multiple arguments

7-element Vector{Int64}:
 1
 2
 3
 1
 2
 1
 2

In [45]:
m1 = rand(3, 4)

3×4 Matrix{Float64}:
 0.297582   0.337536  0.924545   0.314131
 0.0461591  0.917946  0.0445143  0.0392121
 0.351844   0.272086  0.385156   0.57705

In [46]:
m2 = rand(4, 3)

4×3 Matrix{Float64}:
 0.345543  0.811557   0.546003
 0.223127  0.844452   0.995264
 0.191744  0.37651    0.335676
 0.772514  0.0800401  0.280137

In [48]:
# matrix multiplication just works out of the box
m1 * m2

3×3 Matrix{Float64}:
 0.598087  0.899782  0.896765
 0.259596  0.832521  0.964729
 0.701918  0.706508  0.753846

In [49]:
m, n = 5, 5
A = zeros(m ,n)

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [50]:
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end

In [51]:
A

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [52]:
# this can be done more concisely
B = zeros(m, n)

5×5 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [53]:
for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [54]:
# the more "julian" way to do this is via array comprehension
C = [i + j for i in 1:n, j in 1:m]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [55]:
display(C) # can be used as an alternative to print

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

# Conditionals

In [56]:
b = 5
if b == 2
    println("hi")
elseif b == 6
    println("there")
else
    println("ss")
end

ss


In [60]:
# ternary assignment is also a thing
x = b == 5 ? "hi" : "there"
x

"hi"

In [61]:
# short circuit eval also
(1 < 2) && println("this works")

this works


In [62]:
(1 > 2) && println("this works")

false

# Functions

In [63]:
# normal way to declare a function
function hello(name)
    println("Hi there $name")
end
hello("Benjamin")

Hi there Benjamin


In [64]:
# return statements are implicit
function f(x)
    x ^ 2
end
x = f(3)
x

9

In [66]:
# these can be madie into one liners
hello_one(name) = println("Hello $name")
f_one(x) = x ^ 2
hello_one("Melania")
f_one(3)

Hello Melania


9

In [67]:
# anonymous functions are also a thing
g = x -> x ^ 3
g(4)

64

In [68]:
g

#11 (generic function with 1 method)

In [72]:
# julia uses duck typing
# this means that julia functions will work with anything you pass to it so long as the operation the
# function performs is sensible
# e.g.
A = rand(3, 3)
display(g(A)) # this works since the cube of a matrix is well defined
l = [1, 2, 3] # this is a vector, the cube of a vector is not well defined, hence
g(l) # throws an error

3×3 Matrix{Float64}:
 1.92116  2.04366  0.943344
 2.11453  2.30141  1.09502
 1.21145  1.29185  0.648337

MethodError: MethodError: no method matching ^(::Vector{Int64}, ::Int64)
Closest candidates are:
  ^(!Matched::Union{AbstractChar, AbstractString}, ::Integer) at strings/basic.jl:730
  ^(!Matched::LinearAlgebra.Diagonal, ::Integer) at ~/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:208
  ^(!Matched::LinearAlgebra.Diagonal, ::Real) at ~/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:207
  ...

In [73]:
l1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # this is not a matrix

3-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5, 6]
 [7, 8, 9]

In [75]:
g(l1) # again it does not work

MethodError: MethodError: no method matching ^(::Vector{Vector{Int64}}, ::Int64)
Closest candidates are:
  ^(!Matched::Union{AbstractChar, AbstractString}, ::Integer) at strings/basic.jl:730
  ^(!Matched::LinearAlgebra.Diagonal, ::Integer) at ~/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:208
  ^(!Matched::LinearAlgebra.Diagonal, ::Real) at ~/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:207
  ...

In [76]:
# mutating vs non-mutating functions
# the convention is that mutating functions are followed by !
# e.g.
v = [3, 5, 8, 2, 1]
sort(v)

5-element Vector{Int64}:
 1
 2
 3
 5
 8

In [78]:
v # v has not been mutated

5-element Vector{Int64}:
 3
 5
 8
 2
 1

In [79]:
# however
sort!(v)
v

5-element Vector{Int64}:
 1
 2
 3
 5
 8

In [81]:
# broadcasting
# placing a . between any function name and its argument list
g.(l) 
# remember that g(x) = x ^ 3, which wouldn't normally work on a vector
# with broadcasting we can say, cube each individual element 

3-element Vector{Int64}:
  1
  8
 27

In [82]:
A = [i + 3 * j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [83]:
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [84]:
f.(A) # make careful note of the difference here, this is a very powerful concept

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [85]:
split_word = x -> split(x)
sentences = ["this is", "this is also", "more words and spaces"]
split_word(sentences) # won't work

MethodError: MethodError: no method matching split(::Vector{String})
Closest candidates are:
  split(!Matched::AbstractString; limit, keepempty) at strings/util.jl:600
  split(!Matched::T, !Matched::Any; limit, keepempty) where T<:AbstractString at strings/util.jl:592

In [87]:
split_word.(sentences) # magic, who needs the map operation

3-element Vector{Vector{SubString{String}}}:
 ["this", "is"]
 ["this", "is", "also"]
 ["more", "words", "and", "spaces"]

In [88]:
map(x -> split(x), sentences)

3-element Vector{Vector{SubString{String}}}:
 ["this", "is"]
 ["this", "is", "also"]
 ["more", "words", "and", "spaces"]

In [90]:
l = [1, 2, 3, 4, 5, 6, 7, 8]
filter(x -> x % 2 == 0, l)

4-element Vector{Int64}:
 2
 4
 6
 8