# Multiple Dispatch

In [1]:
# to understand multiple dispatch lets look at the + operator
methods(+)

# 206 methods for generic function "+":
[1] +(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:87
[2] +(x::T, y::T) where T<:Union{Float16, Float32, Float64} in Base at float.jl:383
[3] +(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigInt) in Base.GMP at gmp.jl:531
[4] +(c::Union{Int16, Int32, Int64, Int8}, x::BigInt) in Base.GMP at gmp.jl:537
[5] +(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigFloat) in Base.MPFR at mpfr.jl:398
[6] +(c::Union{Int16, Int32, Int64, Int8}, x::BigFloat) in Base.MPFR at mpfr.jl:406
[7] +(c::Union{Float16, Float32, Float64}, x::BigFloat) in Base.MPFR at mpfr.jl:414
[8] +(x::Union{Dates.CompoundPeriod, Dates.Period}) in Dates at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/Dates/src/periods.jl:378
[9] +(x::P, y::P) where P<:Dates.Period in Dates at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/Dates/src/periods.jl:77
[10] +(x::Dates.Period, y::Dates.Period) in Dates at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/Dates/src/periods.jl:367
[11] +(y::Dates.Period, x::Dates.CompoundPeriod) in Dates at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/Dates/src/periods.jl:369
[12] +(y::Dates.Period, x::Dates.TimeType) in Dates at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/Dates/src/arithmetic.jl:85
[13] +(x::Dates.Period, r::AbstractRange{<:Dates.TimeType}) in Dates at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/Dates/src/ranges.jl:63
[14] +(y::Union{Dates.CompoundPeriod, Dates.Period}, x::AbstractArray{<:Dates.TimeType}) in Dates at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/Dates/src/deprecated.jl:14
[15] +(A::LinearAlgebra.SymTridiagonal, B::LinearAlgebra.SymTridiagonal) in LinearAlgebra at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/tridiag.jl:207
[16] +(A::LinearAlgebra.SymTridiagonal, B::LinearAlgebra.Symmetric) in LinearAlgebra at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/symmetric.jl:485
[17] +(A::LinearAlgebra.SymTridiagonal{var"#s882", V} where {var"#s882"<:Real, V<:AbstractVector{var"#s882"}}, B::LinearAlgebra.Hermitian) in LinearAlgebra at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/symmetric.jl:487
[18] +(x::LinearAlgebra.SymTridiagonal, H::LinearAlgebra.UpperHessenberg) in LinearAlgebra at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/hessenberg.jl:109
[19] +(A::LinearAlgebra.SymTridiagonal, B::LinearAlgebra.Diagonal) in LinearAlgebra at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/special.jl:157
[20] +(A::LinearAlgebra.SymTridiagonal, B::LinearAlgebra.Tridiagonal) in LinearAlgebra at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/special.jl:171
[21] +(A::LinearAlgebra.SymTridiagonal, B::LinearAlgebra.Bidiagonal) in LinearAlgebra at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/special.jl:225
[22] +(A::LinearAlgebra.SymTridiagonal{var"#s884", V} where {var"#s884"<:Number, V<:AbstractVector{var"#s884"}}, B::LinearAlgebra.UniformScaling) in LinearAlgebra at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/special.jl:243
[23] +(A::BitArray, B::BitArray) in Base at bitarray.jl:1184
[24] +(Da::LinearAlgebra.Diagonal, Db::LinearAlgebra.Diagonal) in LinearAlgebra at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:184
[25] +(D::LinearAlgebra.Diagonal, S::LinearAlgebra.Symmetric) in LinearAlgebra at /home/benjamin-pop/Development/julia-1.8.0/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:188
[26] +(D::LinearAlgebra.Diagonal{var"#s884", V} where {var"#s884"<:Real, V<:AbstractVector{var"#s884"}}, H::LinearAlgebra.H

In [2]:
@which 3 + 3

+(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:87

In [3]:
@which 3.0 + 3

+(x::Number, y::Number) in Base at promotion.jl:388

In [4]:
@which 3.0 + 3.0 

+(x::T, y::T) where T<:Union{Float16, Float32, Float64} in Base at float.jl:383

In [5]:
# we can extend +
import Base: +

In [7]:
+(x::String, y::String) = string(x, y)

+ (generic function with 207 methods)

In [8]:
@which "hello " + "world"

+(x::String, y::String) in Main at /home/benjamin-pop/Code/julia-learning/julia-academy/introduction_to_julia/other_topics.ipynb:1

In [9]:
foo(x, y) = println("s")
methods(foo)

# 1 method for generic function "foo":
[1] foo(x, y) in Main at /home/benjamin-pop/Code/julia-learning/julia-academy/introduction_to_julia/other_topics.ipynb:1

# Structs in Julia

In [12]:
# structs are similar to classes and types
struct MyObj
    field1
    field2
end

In [13]:
myobj1 = MyObj("Hello", "World")

MyObj("Hello", "World")

In [14]:
myobj1.field1

"Hello"

In [15]:
# structs are immutable by default
# can be mutable
mutable struct Person
    name::String
    age::Int8
    hobbies::Array{String}
end


In [17]:
p = Person("james", 19, ["Fishing", "Hiking"])

Person("james", 19, ["Fishing", "Hiking"])

In [18]:
p.age += 1

20

In [20]:
p

Person("james", 20, ["Fishing", "Hiking"])

In [25]:
# lets use a custom constructor

mutable struct Person2
    name::String
    age::Int8
    isActive::Bool

    function Person2(name::String, age::Int8)
        new(name, age, true) # this creates the object itself
    end
end

In [27]:
p2 = Person2("john", convert(Int8, 2))

Person2("john", 2, true)

In [30]:
function birthday!(p::Person2) # again, like both classes and types
    p.age += 1
end

birthday!(p2)
p2

Person2("john", 4, true)

# Julia is Fast!

In [33]:
a = rand(10^7)

10000000-element Vector{Float64}:
 0.561940562376959
 0.37527877650414665
 0.6247700287536335
 0.6005968778290959
 0.9626307052147816
 0.4443091909537332
 0.11787451894652246
 0.9728034086971891
 0.4896548636021416
 0.5868507914251642
 ⋮
 0.9178434536797125
 0.3699565436592571
 0.6448104409854938
 0.3360071916223579
 0.17673070746834396
 0.2227050114903415
 0.5958623628049574
 0.46902995190149777
 0.2584363033199625

In [34]:
sum(a)

5.000976656617494e6

In [38]:
using BenchmarkTools
using Libdl

In [44]:
# lets compare to c and python - julia can call c natively
C_code = """
#include <stddef.h>
double c_sum(size_t n, double *X) {
    double s = 0.0;
    for (size_t i = 0; i < n; ++i) {
        s += X[i];
    }
    return s;
}
"""

const Clib = tempname()
open(`gcc -fPIC -O3 -msse3 -xc -shared -o $(Clib * "." * Libdl.dlext) -`, "w") do f
    print(f, C_code)
end

c_sum(X::Array{Float64}) = ccall(("c_sum", Clib), Float64, (Csize_t, Ptr{Float64}), length(X), X)

c_sum (generic function with 1 method)

In [45]:
c_sum(a)

5.000976656617835e6

In [46]:
c_sum(a) ≈ sum(a)

true

In [49]:
# ≈ is an alias for the isapprox function
≈

isapprox (generic function with 9 methods)

In [59]:
c_bench = @benchmark c_sum($a)

BenchmarkTools.Trial: 281 samples with 1 evaluation.
 Range (min … max):  10.823 ms … 20.503 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     18.974 ms              ┊ GC (median):    0.00%
 Time  (mean ± σ):   17.796 ms ±  2.694 ms  ┊ GC (mean ± σ):  0.00% ± 0.00%

      ▁                                                ▁█▇▄▁   
  ▄▄▇▇█▇▅▆▅▇▄▆▅▄▄▄▁▄▄▁▁▁▅▁▄▁▁▄▁▁▁▄▁▁▁▁▁▁▁▁▁▄▁▁▁▁▁▁▁▄▄▁▄█████▇ ▅
  10.8 ms      Histogram: log(frequency) by time      19.6 ms <

 Memory estimate: 0 bytes, allocs estimate: 0.

In [60]:
julia_bench = @benchmark sum(a)

BenchmarkTools.Trial: 1107 samples with 1 evaluation.
 Range (min … max):  3.963 ms …   6.152 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     4.288 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   4.507 ms ± 460.071 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

     ▇▇█▅▃▄▂▁                                                  
  ▂▁▃█████████▆▅▄▄▄▃▄▄▄▄▄▄▄▃▃▄▄▅▄▅▄▄▅▅▄▅▄▃▃▃▃▃▂▃▄▃▃▂▃▃▂▃▃▂▃▂▂ ▄
  3.96 ms         Histogram: frequency by time        5.78 ms <

 Memory estimate: 16 bytes, allocs estimate: 1.

In [63]:
using PyCall

In [66]:
apy_list = PyCall.array2py(a)
pysum = pybuiltin("sum")

PyObject <built-in function sum>

In [67]:
pysum(a)

5.000976656617835e6

In [68]:
pysum(a) ≈ sum(a)

true

In [69]:
py_bench = @benchmark pysum(a)

BenchmarkTools.Trial: 5 samples with 1 evaluation.
 Range (min … max):  1.132 s …  1.146 s  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     1.139 s             ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.139 s ± 6.907 ms  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▁   ▁                      ▁                           █  
  █▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  1.13 s        Histogram: frequency by time        1.15 s <

 Memory estimate: 240 bytes, allocs estimate: 6.

In [71]:
# numpy
using Conda
Conda.add("numpy")

┌ Info: Downloading miniconda installer ...
└ @ Conda /home/benjamin-pop/.julia/packages/Conda/x2UxR/src/Conda.jl:193


PREFIX=/home/benjamin-pop/.julia/conda/3


┌ Info: Installing miniconda ...
└ @ Conda /home/benjamin-pop/.julia/packages/Conda/x2UxR/src/Conda.jl:203


Unpacking payload ...


Extracting python-3.10.6-h582c2e5_0_cpython.tar.bz2


Extracting _libgcc_mutex-0.1-conda_forge.tar.bz2
Extracting ca-certificates-2022.6.15-ha878542_0.tar.bz2


Extracting ld_impl_linux-64-2.36.1-hea4e1c9_2.tar.bz2


Extracting tzdata-2022c-h191b570_0.tar.bz2


Extracting libgomp-12.1.0-h8d9b700_16.tar.bz2


Extracting _openmp_mutex-4.5-2_gnu.tar.bz2
Extracting libgcc-ng-12.1.0-h8d9b700_16.tar.bz2


Extracting bzip2-1.0.8-h7f98852_4.tar.bz2


Extracting libffi-3.4.2-h7f98852_5.tar.bz2
Extracting libnsl-2.0.0-h7f98852_0.tar.bz2
Extracting libuuid-2.32.1-h7f98852_1000.tar.bz2
Extracting libzlib-1.2.12-h166bdaf_2.tar.bz2
Extracting ncurses-6.3-h27087fc_1.tar.bz2


Extracting openssl-1.1.1q-h166bdaf_0.tar.bz2


Extracting xz-5.2.6-h166bdaf_0.tar.bz2


Extracting yaml-0.2.5-h7f98852_2.tar.bz2
Extracting libsqlite-3.39.2-h753d276_1.tar.bz2


Extracting readline-8.1.2-h0f457ee_0.tar.bz2
Extracting tk-8.6.12-h27826a3_0.tar.bz2


Extracting charset-normalizer-2.1.1-pyhd8ed1ab_0.tar.bz2
Extracting colorama-0.4.5-pyhd8ed1ab_0.tar.bz2
Extracting idna-3.3-pyhd8ed1ab_0.tar.bz2


Extracting pycparser-2.21-pyhd8ed1ab_0.tar.bz2
Extracting python_abi-3.10-2_cp310.tar.bz2
Extracting six-1.16.0-pyh6c4a22f_0.tar.bz2
Extracting toolz-0.12.0-pyhd8ed1ab_0.tar.bz2
Extracting wheel-0.37.1-pyhd8ed1ab_0.tar.bz2
Extracting certifi-2022.6.15-py310hff52083_0.tar.bz2
Extracting cffi-1.15.1-py310h255011f_0.tar.bz2


Extracting pycosat-0.6.3-py310h5764c6d_1010.tar.bz2
Extracting pysocks-1.7.1-py310hff52083_5.tar.bz2
Extracting ruamel_yaml-0.15.80-py310h5764c6d_1007.tar.bz2
Extracting setuptools-65.2.0-py310hff52083_0.tar.bz2


Extracting tqdm-4.64.0-pyhd8ed1ab_0.tar.bz2


Extracting brotlipy-0.7.0-py310h5764c6d_1004.tar.bz2
Extracting conda-package-handling-1.8.1-py310h5764c6d_1.tar.bz2


Extracting cryptography-37.0.4-py310h597c629_0.tar.bz2


Extracting pip-22.2.2-pyhd8ed1ab_0.tar.bz2


Extracting pyopenssl-22.0.0-pyhd8ed1ab_0.tar.bz2
Extracting urllib3-1.26.11-pyhd8ed1ab_0.tar.bz2
Extracting requests-2.28.1-pyhd8ed1ab_0.tar.bz2
Extracting conda-4.14.0-py310hff52083_0.tar.bz2



                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache



Transaction

  Prefix: /home/benjamin-pop/.julia/conda/3

  Updating specs:

   - python==3.10.6=h582c2e5_0_cpython
   - _libgcc_mutex==0.1=conda_forge
   - ca-certificates==2022.6.15=ha878542_0
   - ld_impl_linux-64==2.36.1=hea4e1c9_2
   - tzdata==2022c=h191b570_0
   - libgomp==12.1.0=h8d9b700_16
   - _openmp_mutex==4.5=2_gnu
   - libgcc-ng==12.1.0=h8d9b700_16
   - bzip2==1.0.8=h7f98852_4
   - libffi==3.4.2=h7f98852_5
   - libnsl==2.0.0=h7f98852_0
   - libuuid==2.32.1=h7f98852_1000
   - libzlib==1.2.12=h166bdaf_2
   - ncurses==6.3=h27087fc_1
   - openssl==1.1.1q=h166bdaf_0
   - xz==5.2.6=h166bdaf_0
   - yaml==0.2.5=h7f98852_2
   - libsqlite==3.39.2=h753d276_1
   - readline==8.1.2=h0f457ee_0
   - tk==8.6.12=h27826a3_0
   - charset-normalizer==2.1.1=pyhd8ed1ab_0
   - colorama==0.4.5=pyhd8ed1ab_0
   - idna==3.3=pyhd8ed1ab_0
   - pycparser==2.21=pyhd8ed1ab_0
   - python_abi==3.10=2_cp310
   - six==1.16.0=pyh6c4a22f_0
   - toolz==0.12.0=pyhd8ed1ab_0
   - wheel==0.37.1=pyhd8ed1ab_0
   - ce

Linking libgcc-ng-12.1.0-h8d9b700_16
Linking yaml-0.2.5-h7f98852_2
Linking xz-5.2.6-h166bdaf_0
Linking openssl-1.1.1q-h166bdaf_0
Linking ncurses-6.3-h27087fc_1


Linking libzlib-1.2.12-h166bdaf_2
Linking libuuid-2.32.1-h7f98852_1000
Linking libnsl-2.0.0-h7f98852_0
Linking libffi-3.4.2-h7f98852_5
Linking bzip2-1.0.8-h7f98852_4
Linking readline-8.1.2-h0f457ee_0
Linking tk-8.6.12-h27826a3_0
Linking libsqlite-3.39.2-h753d276_1
Linking tzdata-2022c-h191b570_0
Linking python-3.10.6-h582c2e5_0_cpython


Linking python_abi-3.10-2_cp310
Linking setuptools-65.2.0-py310hff52083_0
Linking wheel-0.37.1-pyhd8ed1ab_0


Linking pip-22.2.2-pyhd8ed1ab_0
Linking toolz-0.12.0-pyhd8ed1ab_0
Linking six-1.16.0-pyh6c4a22f_0
Linking pycparser-2.21-pyhd8ed1ab_0
Linking idna-3.3-pyhd8ed1ab_0
Linking colorama-0.4.5-pyhd8ed1ab_0
Linking charset-normalizer-2.1.1-pyhd8ed1ab_0
Linking tqdm-4.64.0-pyhd8ed1ab_0
Linking ruamel_yaml-0.15.80-py310h5764c6d_1007
Linking pysocks-1.7.1-py310hff52083_5


Linking pycosat-0.6.3-py310h5764c6d_1010
Linking certifi-2022.6.15-py310hff52083_0
Linking cffi-1.15.1-py310h255011f_0
Linking conda-package-handling-1.8.1-py310h5764c6d_1
Linking cryptography-37.0.4-py310h597c629_0
Linking brotlipy-0.7.0-py310h5764c6d_1004
Linking pyopenssl-22.0.0-pyhd8ed1ab_0
Linking urllib3-1.26.11-pyhd8ed1ab_0
Linking requests-2.28.1-pyhd8ed1ab_0
Linking conda-4.14.0-py310hff52083_0


Transaction finished
installation finished.


┌ Info: Running `conda install -y numpy` in root environment
└ @ Conda /home/benjamin-pop/.julia/packages/Conda/x2UxR/src/Conda.jl:127


done
Solving environment: ...working... 

done



## Package Plan ##

  environment location: /home/benjamin-pop/.julia/conda/3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.6.15.1|       ha878542_0         150 KB  conda-forge
    certifi-2022.6.15.1        |     pyhd8ed1ab_0         155 KB  conda-forge
    libblas-3.9.0              |16_linux64_openblas          13 KB  conda-forge
    libcblas-3.9.0             |16_linux64_openblas          13 KB  conda-forge
    libgfortran-ng-12.1.0      |      h69a702a_16          23 KB  conda-forge
    libgfortran5-12.1.0        |      hdcd56e2_16         1.8 MB  conda-forge
    liblapack-3.9.0            |16_linux64_openblas          13 KB  conda-forge
    libopenblas-0.3.21         |pthreads_h78a6416_3        10.1 MB  conda-forge
    libstdcxx-ng-12.1.0        |      ha89aaad_16         4.3 MB  conda-forge
    numpy-1.23.2           

libcblas-3.9.0       | 13 KB     | ########## | 100% 
libstdcxx-ng-12.1.0  | 4.3 MB    |            |   0% 

libstdcxx-ng-12.1.0  | 4.3 MB    | #3         |  13% 

libstdcxx-ng-12.1.0  | 4.3 MB    | ####2      |  43% 

libstdcxx-ng-12.1.0  | 4.3 MB    | ######9    |  70% 

libstdcxx-ng-12.1.0  | 4.3 MB    | #########8 |  99% 

libstdcxx-ng-12.1.0  | 4.3 MB    | ########## | 100% 
certifi-2022.6.15.1  | 155 KB    |            |   0% 

certifi-2022.6.15.1  | 155 KB    | ########## | 100% 
liblapack-3.9.0      | 13 KB     | ########## | 100% 
libblas-3.9.0        | 13 KB     |            |   0% 

libblas-3.9.0        | 13 KB     | ########## | 100% 
libgfortran-ng-12.1. | 23 KB     | ########## | 100% 
numpy-1.23.2         | 7.1 MB    |            |   0% 

numpy-1.23.2         | 7.1 MB    | #1         |  11% 

numpy-1.23.2         | 7.1 MB    | ##6        |  26% 

numpy-1.23.2         | 7.1 MB    | ####4      |  44% 

numpy-1.23.2         | 7.1 MB    | #####9     |  59% 

numpy-1.23.2         | 7.1 MB    | #######4   |  74% 

numpy-1.23.2         | 7.1 MB    | #########1 |  92% 

numpy-1.23.2         | 7.1 MB    | ########## | 100% 
ca-certificates-2022 | 150 KB    | ########## | 100% 
libopenblas-0.3.21   | 10.1 MB   |            |   0% 

libopenblas-0.3.21   | 10.1 MB   | 8          |   8% 

libopenblas-0.3.21   | 10.1 MB   | #8         |  19% 

libopenblas-0.3.21   | 10.1 MB   | ###1       |  32% 

libopenblas-0.3.21   | 10.1 MB   | ####2      |  43% 

libopenblas-0.3.21   | 10.1 MB   | #####3     |  54% 

libopenblas-0.3.21   | 10.1 MB   | ######4    |  65% 

libopenblas-0.3.21   | 10.1 MB   | #######5   |  76% 

libopenblas-0.3.21   | 10.1 MB   | ########6  |  87% 

libopenblas-0.3.21   | 10.1 MB   | #########8 |  98% 

libopenblas-0.3.21   | 10.1 MB   | ########## | 100% 
libgfortran5-12.1.0  | 1.8 MB    |            |   0% 

libgfortran5-12.1.0  | 1.8 MB    | ####2      |  43% 

libgfortran5-12.1.0  | 1.8 MB    | ########## | 100% 
Preparing transaction: ...working... 

done
Verifying transaction: ...working... 

done
Executing transaction: ...working... 

done


Retrieving notices: ...working... 

done


In [72]:
numpy_sum = pyimport("numpy")["sum"]
apy_numpy = PyObject(a)

np_bench = @benchmark numpy_sum(apy_numpy)

BenchmarkTools.Trial: 612 samples with 1 evaluation.
 Range (min … max):  6.444 ms …  12.393 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     8.138 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   8.152 ms ± 881.341 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

       ▂  ▅▁▁ ▂ ▁▄      ▇▂▇▃▄▇▇█▄ ▂      ▃ ▁ ▂                 
  ▃▃▃▅▄█▅▇███▆█▇████▆█▅████████████▆▆█▇▆▇█▆█▆██▇▅▆▄▄▅▃▄▄▃▄▁▃▃ ▅
  6.44 ms         Histogram: frequency by time        10.2 ms <

 Memory estimate: 32 bytes, allocs estimate: 2.

# Basic LinAlg

In [74]:
A = rand(1:4, 3, 3)

3×3 Matrix{Int64}:
 3  3  1
 4  4  4
 2  3  3

In [83]:
B = A # here B and A reference the same object in memory, so changes to A will reflect in B and vice versa
C = copy(A) # new object
[B C]

3×6 Matrix{Int64}:
 17  3  1  17  3  1
  4  4  4   4  4  4
  2  3  3   2  3  3

In [84]:
A[1, 1] = 17

17

In [85]:
A

3×3 Matrix{Int64}:
 17  3  1
  4  4  4
  2  3  3

In [86]:
[B C]

3×6 Matrix{Int64}:
 17  3  1  17  3  1
  4  4  4   4  4  4
  2  3  3   2  3  3

In [87]:
x = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [88]:
b = A * x

3-element Vector{Float64}:
 21.0
 12.0
  8.0

In [89]:
Asym = A + A'

3×3 Matrix{Int64}:
 34  7  3
  7  8  7
  3  7  6

In [90]:
Apd = A'A

3×3 Matrix{Int64}:
 309  73  39
  73  34  28
  39  28  26

In [92]:
# solving linear systems can be as simple as
A \ b # this solves Ax = b

3-element Vector{Float64}:
 1.0000000000000004
 0.9999999999999964
 1.000000000000003

In [93]:
# if there is not a unique solution?
Atall = A[:, 1:2]

3×2 Matrix{Int64}:
 17  3
  4  4
  2  3

In [94]:
Atall \ b # it also works for rand deficient matrix!

2-element Vector{Float64}:
 0.8613096387869426
 2.121305775545683

In [95]:
A = randn(3, 3)

3×3 Matrix{Float64}:
 -0.463926   0.30945    0.368831
 -0.147648  -0.425539  -0.239908
 -1.22545   -1.60859    0.985376

In [96]:
Singular = [A[:, 1] A[:, 1]]

3×2 Matrix{Float64}:
 -0.463926  -0.463926
 -0.147648  -0.147648
 -1.22545   -1.22545

In [98]:
Singular \ b # in this case julia yields the solution with the smallest norm 

2-element Vector{Float64}:
 -6.1302253266613995
 -6.130225326661403

# Factorizations

In [104]:
using LinearAlgebra

In [105]:
A = randn(3, 3) # this is random normal (rand is uniform)

3×3 Matrix{Float64}:
  1.05582  -0.593841  -0.18566
 -1.0181    0.189658  -1.09987
  1.74688   0.44029   -0.142958

In [107]:
# LU decomposition (remember PA = LU) * P is the Permutation matrix
l, u, p = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
  1.0        0.0       0.0
  0.604407   1.0       0.0
 -0.582812  -0.518939  1.0
U factor:
3×3 Matrix{Float64}:
 1.74688   0.44029   -0.142958
 0.0      -0.859955  -0.0992549
 0.0       0.0       -1.2347

In [108]:
p

3-element Vector{Int64}:
 3
 1
 2

In [109]:
l

3×3 Matrix{Float64}:
  1.0        0.0       0.0
  0.604407   1.0       0.0
 -0.582812  -0.518939  1.0

In [110]:
u

3×3 Matrix{Float64}:
 1.74688   0.44029   -0.142958
 0.0      -0.859955  -0.0992549
 0.0       0.0       -1.2347

In [113]:
# pivoting is on by default so we cannot assume A == LU
l*u

3×3 Matrix{Float64}:
  1.74688   0.44029   -0.142958
  1.05582  -0.593841  -0.18566
 -1.0181    0.189658  -1.09987

In [118]:
A

3×3 Matrix{Float64}:
  1.05582  -0.593841  -0.18566
 -1.0181    0.189658  -1.09987
  1.74688   0.44029   -0.142958

In [119]:
# but if we first pivot a we get the correct result
A[p,:] # notice the notation here for pivoting
# since p = [3, 1, 2] the pivot operation is saying, row 3 then 1 then 2 and all columns of A

3×3 Matrix{Float64}:
  1.74688   0.44029   -0.142958
  1.05582  -0.593841  -0.18566
 -1.0181    0.189658  -1.09987

In [126]:
# solving systems can then be performed as follows
x = ones(3)
b = A * x

3-element Vector{Float64}:
  0.27632263808599494
 -1.9283125745836953
  2.0442075989630824

In [167]:
display(A)
l, u, p = lu(A, NoPivot())

3×3 Matrix{Float64}:
  1.05582  -0.593841  -0.18566
 -1.0181    0.189658  -1.09987
  1.74688   0.44029   -0.142958

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
  1.0        0.0      0.0
 -0.964271   1.0      0.0
  1.65451   -3.71524  1.0
U factor:
3×3 Matrix{Float64}:
 1.05582  -0.593841  -0.18566
 0.0      -0.382966  -1.2789
 0.0       0.0       -4.58719

In [168]:
(l * u)

3×3 Matrix{Float64}:
  1.05582  -0.593841  -0.18566
 -1.0181    0.189658  -1.09987
  1.74688   0.44029   -0.142958

In [170]:
u * x

3-element Vector{Float64}:
  0.27632263808599494
 -1.6618627947621496
 -4.587192549106617

In [171]:
l \ b

3-element Vector{Float64}:
  0.27632263808599494
 -1.6618627947621494
 -4.587192549106617

In [174]:
l, u, p = lu(A, NoPivot())
# PA = LU
# A = P'LU
# then
# b = P'LUx
# LUx = Pb
# Ux = L \ Pb
# x = U \ L \ Pb

u \ (l \ b[p])

3-element Vector{Float64}:
 0.9999999999999998
 0.9999999999999997
 1.0

In [177]:
(l * u) \ b[p]

3-element Vector{Float64}:
 1.0
 1.0000000000000002
 0.9999999999999998

In [178]:
det(A)

1.8548035720980491

In [180]:
det(l * u)

1.8548035720980491

In [181]:
# QR factorization
Aqr = qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.462882   0.764875  -0.448003
  0.446343  -0.235542  -0.863306
 -0.765845  -0.599572  -0.232369
R factor:
3×3 Matrix{Float64}:
 -2.28098   0.0223367  -0.295498
  0.0      -0.762872    0.202773
  0.0       0.0         1.06592

In [185]:
A

3×3 Matrix{Float64}:
  1.05582  -0.593841  -0.18566
 -1.0181    0.189658  -1.09987
  1.74688   0.44029   -0.142958

In [184]:
Aqr.Q * Aqr.R

3×3 Matrix{Float64}:
  1.05582  -0.593841  -0.18566
 -1.0181    0.189658  -1.09987
  1.74688   0.44029   -0.142958

In [186]:
(Aqr.Q * Aqr.R) \ b

3-element Vector{Float64}:
 1.0000000000000002
 0.9999999999999991
 0.9999999999999997

# Eigen Decomposition and SVD

In [192]:
D = Diagonal([1, 2, 3])
display(D)
DEig = eigen(D)

3×3 Diagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

Eigen{Float64, Int64, Matrix{Float64}, Vector{Int64}}
values:
3-element Vector{Int64}:
 1
 2
 3
vectors:
3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [193]:
# singular value decomposition SVD
S = svd(A)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
3×3 Matrix{Float64}:
 -0.442519  -0.190495  -0.876293
  0.515372  -0.853707  -0.0746728
 -0.733872  -0.484661   0.475957
singular values:
3-element Vector{Float64}:
 2.3057043913249182
 1.0907729728785949
 0.7374964403134963
Vt factor:
3×3 Matrix{Float64}:
 -0.986209    0.0162265  -0.16471
 -0.163748   -0.240362    0.956772
 -0.0240648   0.970548    0.239704

In [194]:
# special matrix structures
A = randn(3, 3)

3×3 Matrix{Float64}:
 -0.864194  -0.844664   0.583161
  0.138976   1.56283   -1.47919
 -0.902463  -0.110518  -0.672286

In [195]:
Diagonal(diag(A))

3×3 Diagonal{Float64, Vector{Float64}}:
 -0.864194   ⋅         ⋅ 
   ⋅        1.56283    ⋅ 
   ⋅         ⋅       -0.672286

In [196]:
LowerTriangular(A)

3×3 LowerTriangular{Float64, Matrix{Float64}}:
 -0.864194    ⋅          ⋅ 
  0.138976   1.56283     ⋅ 
 -0.902463  -0.110518  -0.672286

In [197]:
UpperTriangular(A)

3×3 UpperTriangular{Float64, Matrix{Float64}}:
 -0.864194  -0.844664   0.583161
   ⋅         1.56283   -1.47919
   ⋅          ⋅        -0.672286

In [199]:
Symmetric(A) # this will flip by default along the upper triangular

3×3 Symmetric{Float64, Matrix{Float64}}:
 -0.864194  -0.844664   0.583161
 -0.844664   1.56283   -1.47919
  0.583161  -1.47919   -0.672286

In [200]:
SymTridiagonal(diag(A + A'), diag(A + A', 1))

3×3 SymTridiagonal{Float64, Vector{Float64}}:
 -1.72839   -0.705688    ⋅ 
 -0.705688   3.12566   -1.58971
   ⋅        -1.58971   -1.34457

In [205]:
# symmetric eigenproblems
n = 1000
A = randn(n, n)
Asym1 = A + A'
Asym2 = copy(Asym1)
Asym2[1, 2] += 5eps()
println("Asym1 symmetric?: $(issymmetric(Asym1))")
println("Asym1 symmetric?: $(issymmetric(Asym2))")

Asym1 symmetric?: true
Asym1 symmetric?: false


In [206]:
@time eigvals(Asym1)

  0.375018 seconds (274.59 k allocations: 21.434 MiB, 73.11% compilation time)


1000-element Vector{Float64}:
 -88.38048788134319
 -87.36347776046871
 -86.91636812319646
 -86.65131721855238
 -86.05295944539765
 -85.67617275157814
 -85.26716021393126
 -84.59555986568995
 -84.26348372911751
 -83.96643538568152
   ⋮
  84.46335527784308
  84.97233656709535
  85.37228533941942
  85.86921845441795
  86.28736989856648
  86.3500243036957
  87.76767324067421
  88.73993650803062
  89.33987149111928

In [207]:
@time eigvals(Asym2)

  0.785564 seconds (13 allocations: 7.920 MiB, 1.59% gc time)


1000-element Vector{Float64}:
 -88.38048788134337
 -87.36347776046902
 -86.91636812319551
 -86.65131721855334
 -86.05295944539795
 -85.67617275157865
 -85.26716021393146
 -84.59555986569022
 -84.26348372911663
 -83.96643538568121
   ⋮
  84.46335527784291
  84.97233656709558
  85.37228533941934
  85.86921845441789
  86.2873698985673
  86.35002430369549
  87.76767324067319
  88.73993650803088
  89.33987149111942

In [208]:
# for symmetric matrices more optimised methods can be used

In [210]:
# rational systems of linear equations
Ar = convert(Matrix{Rational{Int64}}, rand(1:10, 3, 3)) / 10

3×3 Matrix{Rational{Int64}}:
 1//10  3//5   4//5
 1//10  1//5   1//1
 1//1   7//10  1//10

In [211]:
x = ones(Int, 3)
b = Ar * x

3-element Vector{Rational{Int64}}:
  3//2
 13//10
  9//5

In [212]:
Ar \ b

3-element Vector{Rational{Int64}}:
 1//1
 1//1
 1//1

In [213]:
lu(Ar)

LU{Rational{Int64}, Matrix{Rational{Int64}}, Vector{Int64}}
L factor:
3×3 Matrix{Rational{Int64}}:
 1//1    0//1   0//1
 1//10   1//1   0//1
 1//10  13//53  1//1
U factor:
3×3 Matrix{Rational{Int64}}:
 1//1   7//10     1//10
 0//1  53//100   79//100
 0//1   0//1    211//265

In [215]:
λ₁, λ₂, λ₃ = 1, 0.5, 0.25
v1, v2, v3 = [1, 0, 0], [0, 1, 0], [0, 0, 1]
V, Λ = [v1 v2 v3], Diagonal([λ₁, λ₂, λ₃])
A = V * (Λ / V)

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  0.5  0.0
 0.0  0.0  0.25